//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aylos.Xrm.Sdk.BuildTools.Models.Domain
{
	using Microsoft.Xrm.Sdk;
	using Microsoft.Xrm.Sdk.Client;
	using System;
	using System.CodeDom.Compiler;
	using System.Collections.Generic;
	using System.ComponentModel;
	using System.Linq;
	using System.Runtime.Serialization;
	
	
	/// <summary>
	/// Represents a source of entities bound to a CRM service. It tracks and manages changes made to the retrieved entities.
	/// </summary>
	[GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public partial class CrmServiceContext : OrganizationServiceContext
	{
		
		/// <summary>
		/// Constructor.
		/// </summary>
		public CrmServiceContext(IOrganizationService service) : 
				base(service)
		{
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="WebFile"/> entities.
		/// </summary>
		public IQueryable<WebFile> WebFileSet
		{
			get
			{
				return this.CreateQuery<WebFile>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="WebPage"/> entities.
		/// </summary>
		public IQueryable<WebPage> WebPageSet
		{
			get
			{
				return this.CreateQuery<WebPage>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="WebTemplate"/> entities.
		/// </summary>
		public IQueryable<WebTemplate> WebTemplateSet
		{
			get
			{
				return this.CreateQuery<WebTemplate>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Note"/> entities.
		/// </summary>
		public IQueryable<Note> NoteSet
		{
			get
			{
				return this.CreateQuery<Note>();
			}
		}

		/// <summary>
		/// Gets a binding to the set of all <see cref="SystemJob"/> entities.
		/// </summary>
		public IQueryable<SystemJob> SystemJobSet
		{
			get
			{
				return this.CreateQuery<SystemJob>();
			}
		}

		/// <summary>
		/// Gets a binding to the set of all <see cref="ImportJob"/> entities.
		/// </summary>
		public IQueryable<ImportJob> ImportJobSet
		{
			get
			{
				return this.CreateQuery<ImportJob>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Organization"/> entities.
		/// </summary>
		public IQueryable<Organization> OrganizationSet
		{
			get
			{
				return this.CreateQuery<Organization>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="PlugInAssembly"/> entities.
		/// </summary>
		public IQueryable<PlugInAssembly> PlugInAssemblySet
		{
			get
			{
				return this.CreateQuery<PlugInAssembly>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="PlugInType"/> entities.
		/// </summary>
		public IQueryable<PlugInType> PlugInTypeSet
		{
			get
			{
				return this.CreateQuery<PlugInType>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="SdkMessage"/> entities.
		/// </summary>
		public IQueryable<SdkMessage> SdkMessageSet
		{
			get
			{
				return this.CreateQuery<SdkMessage>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="SdkMessageProcessingStep"/> entities.
		/// </summary>
		public IQueryable<SdkMessageProcessingStep> SdkMessageProcessingStepSet
		{
			get
			{
				return this.CreateQuery<SdkMessageProcessingStep>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="SdkMessageProcessingStepImage"/> entities.
		/// </summary>
		public IQueryable<SdkMessageProcessingStepImage> SdkMessageProcessingStepImageSet
		{
			get
			{
				return this.CreateQuery<SdkMessageProcessingStepImage>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="ServiceEndpoint"/> entities.
		/// </summary>
		public IQueryable<ServiceEndpoint> ServiceEndpointSet
		{
			get
			{
				return this.CreateQuery<ServiceEndpoint>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Solution"/> entities.
		/// </summary>
		public IQueryable<Solution> SolutionSet
		{
			get
			{
				return this.CreateQuery<Solution>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="SolutionComponent"/> entities.
		/// </summary>
		public IQueryable<SolutionComponent> SolutionComponentSet
		{
			get
			{
				return this.CreateQuery<SolutionComponent>();
			}
		}
	}
}
