//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aylos.Xrm.Sdk.BuildTools.Models.Domain
{
	using System.CodeDom.Compiler;
	using System.Runtime.Serialization;
	
	
	[DataContractAttribute()]
	[GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum GlobalComponentType
	{
		
		[EnumMemberAttribute()]
		Entity = 1,
		
		[EnumMemberAttribute()]
		Attribute = 2,
		
		[EnumMemberAttribute()]
		Relationship = 3,
		
		[EnumMemberAttribute()]
		AttributePicklistValue = 4,
		
		[EnumMemberAttribute()]
		AttributeLookupValue = 5,
		
		[EnumMemberAttribute()]
		ViewAttribute = 6,
		
		[EnumMemberAttribute()]
		LocalizedLabel = 7,
		
		[EnumMemberAttribute()]
		RelationshipExtraCondition = 8,
		
		[EnumMemberAttribute()]
		OptionSet = 9,
		
		[EnumMemberAttribute()]
		EntityRelationship = 10,
		
		[EnumMemberAttribute()]
		EntityRelationshipRole = 11,
		
		[EnumMemberAttribute()]
		EntityRelationshipRelationships = 12,
		
		[EnumMemberAttribute()]
		ManagedProperty = 13,
		
		[EnumMemberAttribute()]
		EntityKey = 14,
		
		[EnumMemberAttribute()]
		Privilege = 16,
		
		[EnumMemberAttribute()]
		PrivilegeObjectTypeCode = 17,
		
		[EnumMemberAttribute()]
		Role = 20,
		
		[EnumMemberAttribute()]
		RolePrivilege = 21,
		
		[EnumMemberAttribute()]
		DisplayString = 22,
		
		[EnumMemberAttribute()]
		DisplayStringMap = 23,
		
		[EnumMemberAttribute()]
		Form = 24,
		
		[EnumMemberAttribute()]
		Organization = 25,
		
		[EnumMemberAttribute()]
		SavedQuery = 26,
		
		[EnumMemberAttribute()]
		Workflow = 29,
		
		[EnumMemberAttribute()]
		Report = 31,
		
		[EnumMemberAttribute()]
		ReportEntity = 32,
		
		[EnumMemberAttribute()]
		ReportCategory = 33,
		
		[EnumMemberAttribute()]
		ReportVisibility = 34,
		
		[EnumMemberAttribute()]
		Attachment = 35,
		
		[EnumMemberAttribute()]
		EmailTemplate = 36,
		
		[EnumMemberAttribute()]
		ContractTemplate = 37,
		
		[EnumMemberAttribute()]
		KBArticleTemplate = 38,
		
		[EnumMemberAttribute()]
		MailMergeTemplate = 39,
		
		[EnumMemberAttribute()]
		DuplicateRule = 44,
		
		[EnumMemberAttribute()]
		DuplicateRuleCondition = 45,
		
		[EnumMemberAttribute()]
		EntityMap = 46,
		
		[EnumMemberAttribute()]
		AttributeMap = 47,
		
		[EnumMemberAttribute()]
		RibbonCommand = 48,
		
		[EnumMemberAttribute()]
		RibbonContextGroup = 49,
		
		[EnumMemberAttribute()]
		RibbonCustomization = 50,
		
		[EnumMemberAttribute()]
		RibbonRule = 52,
		
		[EnumMemberAttribute()]
		RibbonTabToCommandMap = 53,
		
		[EnumMemberAttribute()]
		RibbonDiff = 55,
		
		[EnumMemberAttribute()]
		SavedQueryVisualization = 59,
		
		[EnumMemberAttribute()]
		SystemForm = 60,
		
		[EnumMemberAttribute()]
		WebResource = 61,
		
		[EnumMemberAttribute()]
		SiteMap = 62,
		
		[EnumMemberAttribute()]
		ConnectionRole = 63,
		
		[EnumMemberAttribute()]
		ComplexControl = 64,
		
		[EnumMemberAttribute()]
		FieldSecurityProfile = 70,
		
		[EnumMemberAttribute()]
		FieldPermission = 71,
		
		[EnumMemberAttribute()]
		PluginType = 90,
		
		[EnumMemberAttribute()]
		PluginAssembly = 91,
		
		[EnumMemberAttribute()]
		SDKMessageProcessingStep = 92,
		
		[EnumMemberAttribute()]
		SDKMessageProcessingStepImage = 93,
		
		[EnumMemberAttribute()]
		ServiceEndpoint = 95,
		
		[EnumMemberAttribute()]
		RoutingRule = 150,
		
		[EnumMemberAttribute()]
		RoutingRuleItem = 151,
		
		[EnumMemberAttribute()]
		SLA = 152,
		
		[EnumMemberAttribute()]
		SLAItem = 153,
		
		[EnumMemberAttribute()]
		ConvertRule = 154,
		
		[EnumMemberAttribute()]
		ConvertRuleItem = 155,
		
		[EnumMemberAttribute()]
		HierarchyRule = 65,
		
		[EnumMemberAttribute()]
		MobileOfflineProfile = 161,
		
		[EnumMemberAttribute()]
		MobileOfflineProfileItem = 162,
		
		[EnumMemberAttribute()]
		SimilarityRule = 165,
		
		[EnumMemberAttribute()]
		CustomControl = 66,
		
		[EnumMemberAttribute()]
		CustomControlDefaultConfig = 68,
		
		[EnumMemberAttribute()]
		DataSourceMapping = 166,
		
		[EnumMemberAttribute()]
		SDKMessage = 201,
		
		[EnumMemberAttribute()]
		SDKMessageFilter = 202,
		
		[EnumMemberAttribute()]
		SdkMessagePair = 203,
		
		[EnumMemberAttribute()]
		SdkMessageRequest = 204,
		
		[EnumMemberAttribute()]
		SdkMessageRequestField = 205,
		
		[EnumMemberAttribute()]
		SdkMessageResponse = 206,
		
		[EnumMemberAttribute()]
		SdkMessageResponseField = 207,
		
		[EnumMemberAttribute()]
		WebWizard = 210,
		
		[EnumMemberAttribute()]
		Index = 18,
		
		[EnumMemberAttribute()]
		ImportMap = 208,
		
		[EnumMemberAttribute()]
		CanvasApp = 300,
		
		[EnumMemberAttribute()]
		Connector = 371,
		
		[EnumMemberAttribute()]
		EnvironmentVariableDefinition = 380,
		
		[EnumMemberAttribute()]
		EnvironmentVariableValue = 381,
		
		[EnumMemberAttribute()]
		AIProjectType = 400,
		
		[EnumMemberAttribute()]
		AIProject = 401,
		
		[EnumMemberAttribute()]
		AIConfiguration = 402,
		
		[EnumMemberAttribute()]
		EntityAnalyticsConfiguration = 430,
	}
}
