//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aylos.Xrm.Sdk.BuildTools.Models.Domain
{
	using System.CodeDom.Compiler;
	using System.Runtime.Serialization;
	
	
	[DataContractAttribute()]
	[GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum GlobalSelectAnActivityType1
	{
		
		[EnumMemberAttribute()]
		PhoneCall = 4210,
		
		[EnumMemberAttribute()]
		Appointment = 4201,
		
		[EnumMemberAttribute()]
		Letter = 4207,
		
		[EnumMemberAttribute()]
		LetterViaMailMerge = 42070,
		
		[EnumMemberAttribute()]
		Fax = 4204,
		
		[EnumMemberAttribute()]
		FaxViaMailMerge = 42040,
		
		[EnumMemberAttribute()]
		Email = 4202,
		
		[EnumMemberAttribute()]
		EmailViaMailMerge = 42020,
	}
}
