//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aylos.Xrm.Sdk.BuildTools.Models.Domain
{
	using System.CodeDom.Compiler;
	using System.Runtime.Serialization;
	
	
	[DataContractAttribute()]
	[GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum ServiceEndpointAuthenticationTypeForServiceBus
	{
		
		[EnumMemberAttribute()]
		ACS = 1,
		
		[EnumMemberAttribute()]
		SASKey = 2,
		
		[EnumMemberAttribute()]
		SASToken = 3,
		
		[EnumMemberAttribute()]
		WebhookKey = 4,
		
		[EnumMemberAttribute()]
		HttpHeader = 5,
		
		[EnumMemberAttribute()]
		HttpQueryString = 6,
	}
}
