//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aylos.Xrm.Sdk.BuildTools.Models.Domain
{
	using System.CodeDom.Compiler;
	using System.Runtime.Serialization;
	
	
	[DataContractAttribute()]
	[GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.25")]
	public enum SystemJobSystemJobType
	{
		
		[EnumMemberAttribute()]
		SystemEvent = 1,
		
		[EnumMemberAttribute()]
		BulkEmail = 2,
		
		[EnumMemberAttribute()]
		ImportFileParse = 3,
		
		[EnumMemberAttribute()]
		TransformParseData = 4,
		
		[EnumMemberAttribute()]
		Import = 5,
		
		[EnumMemberAttribute()]
		ActivityPropagation = 6,
		
		[EnumMemberAttribute()]
		DuplicateDetectionRulePublish = 7,
		
		[EnumMemberAttribute()]
		BulkDuplicateDetection = 8,
		
		[EnumMemberAttribute()]
		SQMDataCollection = 9,
		
		[EnumMemberAttribute()]
		Workflow = 10,
		
		[EnumMemberAttribute()]
		QuickCampaign = 11,
		
		[EnumMemberAttribute()]
		MatchcodeUpdate = 12,
		
		[EnumMemberAttribute()]
		BulkDelete = 13,
		
		[EnumMemberAttribute()]
		DeletionService = 14,
		
		[EnumMemberAttribute()]
		IndexManagement = 15,
		
		[EnumMemberAttribute()]
		CollectOrganizationStatistics = 16,
		
		[EnumMemberAttribute()]
		ImportSubprocess = 17,
		
		[EnumMemberAttribute()]
		CalculateOrganizationStorageSize = 18,
		
		[EnumMemberAttribute()]
		CollectOrganizationDatabaseStatistics = 19,
		
		[EnumMemberAttribute()]
		CollectionOrganizationSizeStatistics = 20,
		
		[EnumMemberAttribute()]
		DatabaseTuning = 21,
		
		[EnumMemberAttribute()]
		CalculateOrganizationMaximumStorageSize = 22,
		
		[EnumMemberAttribute()]
		BulkDeleteSubprocess = 23,
		
		[EnumMemberAttribute()]
		UpdateStatisticIntervals = 24,
		
		[EnumMemberAttribute()]
		OrganizationFullTextCatalogIndex = 25,
		
		[EnumMemberAttribute()]
		DatabaseLogBackup = 26,
		
		[EnumMemberAttribute()]
		UpdateContractStates = 27,
		
		[EnumMemberAttribute()]
		DBCCSHRINKDATABASEMaintenanceJob = 28,
		
		[EnumMemberAttribute()]
		DBCCSHRINKFILEMaintenanceJob = 29,
		
		[EnumMemberAttribute()]
		ReindexAllIndicesMaintenanceJob = 30,
		
		[EnumMemberAttribute()]
		StorageLimitNotification = 31,
		
		[EnumMemberAttribute()]
		CleanupInactiveWorkflowAssemblies = 32,
		
		[EnumMemberAttribute()]
		RecurringSeriesExpansion = 35,
		
		[EnumMemberAttribute()]
		ImportSampleData = 38,
		
		[EnumMemberAttribute()]
		GoalRollUp = 40,
		
		[EnumMemberAttribute()]
		AuditPartitionCreation = 41,
		
		[EnumMemberAttribute()]
		CheckForLanguagePackUpdates = 42,
		
		[EnumMemberAttribute()]
		ProvisionLanguagePack = 43,
		
		[EnumMemberAttribute()]
		UpdateOrganizationDatabase = 44,
		
		[EnumMemberAttribute()]
		UpdateSolution = 45,
		
		[EnumMemberAttribute()]
		RegenerateEntityRowCountSnapshotData = 46,
		
		[EnumMemberAttribute()]
		RegenerateReadShareSnapshotData = 47,
		
		[EnumMemberAttribute()]
		OutgoingActivity = 50,
		
		[EnumMemberAttribute()]
		IncomingEmailProcessing = 51,
		
		[EnumMemberAttribute()]
		MailboxTestAccess = 52,
		
		[EnumMemberAttribute()]
		EncryptionHealthCheck = 53,
		
		[EnumMemberAttribute()]
		ExecuteAsyncRequest = 54,
		
		[EnumMemberAttribute()]
		PostToYammer = 49,
		
		[EnumMemberAttribute()]
		UpdateEntitlementStates = 56,
		
		[EnumMemberAttribute()]
		CalculateRollupField = 57,
		
		[EnumMemberAttribute()]
		MassCalculateRollupField = 58,
		
		[EnumMemberAttribute()]
		ImportTranslation = 59,
		
		[EnumMemberAttribute()]
		ConvertDateAndTimeBehavior = 62,
		
		[EnumMemberAttribute()]
		EntityKeyIndexCreation = 63,
		
		[EnumMemberAttribute()]
		UpdateKnowledgeArticleStates = 65,
		
		[EnumMemberAttribute()]
		ResourceBookingSync = 68,
		
		[EnumMemberAttribute()]
		RelationshipAssistantCards = 69,
		
		[EnumMemberAttribute()]
		CleanupSolutionComponents = 71,
		
		[EnumMemberAttribute()]
		AppModuleMetadataOperation = 72,
		
		[EnumMemberAttribute()]
		ALMAnomalyDetectionOperation = 73,
		
		[EnumMemberAttribute()]
		FlowNotification = 75,
		
		[EnumMemberAttribute()]
		RibbonClientMetadataOperation = 76,
		
		[EnumMemberAttribute()]
		CallbackRegistrationExpanderOperation = 79,
		
		[EnumMemberAttribute()]
		CascadeAssign = 90,
		
		[EnumMemberAttribute()]
		CascadeDelete = 91,
		
		[EnumMemberAttribute()]
		EventExpanderOperation = 92,
		
		[EnumMemberAttribute()]
		ImportSolutionMetadata = 93,
		
		[EnumMemberAttribute()]
		BulkDeleteFileAttachment = 94,
		
		[EnumMemberAttribute()]
		RefreshBusinessUnitForRecordsOwnedByPrincipal = 95,
		
		[EnumMemberAttribute()]
		RevokeInheritedAccess = 96,
		
		[EnumMemberAttribute()]
		CascadeGrantOrRevokeAccessVersionTrackingAsyncOperation = 12801,
		
		[EnumMemberAttribute()]
		AIBuilderTrainingEvents = 190690091,
		
		[EnumMemberAttribute()]
		AIBuilderPredictionEvents = 190690092,
	}
}
