//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aylos.Xrm.Sdk.BuildTools.Models.Domain
{
	using System.CodeDom.Compiler;
	using System.Runtime.Serialization;
	
	
	[DataContractAttribute()]
	[GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.25")]
	public enum SystemJobStatusReason
	{
		
		[EnumMemberAttribute()]
		WaitingForResources = 0,
		
		[EnumMemberAttribute()]
		Waiting = 10,
		
		[EnumMemberAttribute()]
		InProgress = 20,
		
		[EnumMemberAttribute()]
		Pausing = 21,
		
		[EnumMemberAttribute()]
		Canceling = 22,
		
		[EnumMemberAttribute()]
		Succeeded = 30,
		
		[EnumMemberAttribute()]
		Failed = 31,
		
		[EnumMemberAttribute()]
		Canceled = 32,
	}
}
