//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aylos.Xrm.Sdk.BuildTools.Models.Domain
{
	using System.CodeDom.Compiler;
	using System.Runtime.Serialization;
	
	
	[DataContractAttribute()]
	[GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum WebPageCommentPolicy
	{
		
		[EnumMemberAttribute()]
		Inherit = 756150000,
		
		[EnumMemberAttribute()]
		None = 756150001,
		
		[EnumMemberAttribute()]
		Open = 756150002,
		
		[EnumMemberAttribute()]
		OpenToAuthenticatedUsers = 756150003,
		
		[EnumMemberAttribute()]
		Moderated = 756150004,
		
		[EnumMemberAttribute()]
		Closed = 756150005,
	}
}
