//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared.Models.Domain
{
	using System.CodeDom.Compiler;
	using System.Runtime.Serialization;
	
	
	[DataContractAttribute()]
	[GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.71")]
	public enum AccountPreferredMethodOfContact
	{
		
		[EnumMemberAttribute()]
		Any = 1,
		
		[EnumMemberAttribute()]
		Email = 2,
		
		[EnumMemberAttribute()]
		Phone = 3,
		
		[EnumMemberAttribute()]
		Fax = 4,
		
		[EnumMemberAttribute()]
		Mail = 5,
	}
}
