//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared.Models.Domain
{
	using System.CodeDom.Compiler;
	using System.Runtime.Serialization;
	
	
	[DataContractAttribute()]
	[GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.95")]
	public enum AccountRelationshipType
	{
		
		[EnumMemberAttribute()]
		Competitor = 1,
		
		[EnumMemberAttribute()]
		Consultant = 2,
		
		[EnumMemberAttribute()]
		Customer = 3,
		
		[EnumMemberAttribute()]
		Investor = 4,
		
		[EnumMemberAttribute()]
		Partner = 5,
		
		[EnumMemberAttribute()]
		Influencer = 6,
		
		[EnumMemberAttribute()]
		Press = 7,
		
		[EnumMemberAttribute()]
		Prospect = 8,
		
		[EnumMemberAttribute()]
		Reseller = 9,
		
		[EnumMemberAttribute()]
		Supplier = 10,
		
		[EnumMemberAttribute()]
		Vendor = 11,
		
		[EnumMemberAttribute()]
		Other = 12,
	}
}
