//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared.Models.Domain
{
	using System.CodeDom.Compiler;
	using System.Runtime.Serialization;
	
	
	[DataContractAttribute()]
	[GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.91")]
	public enum AccountPaymentTerms
	{
		
		[EnumMemberAttribute()]
		NetThirty = 1,
		
		[EnumMemberAttribute()]
		TwoTenNetThirty = 2,
		
		[EnumMemberAttribute()]
		NetFortyFive = 3,
		
		[EnumMemberAttribute()]
		NetSixty = 4,
	}
}
