//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared.Models.Domain
{
	using System.CodeDom.Compiler;
	using System.Runtime.Serialization;
	
	
	[DataContractAttribute()]
	[GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.71")]
	public enum AccountIndustry
	{
		
		[EnumMemberAttribute()]
		Accounting = 1,
		
		[EnumMemberAttribute()]
		AgricultureAndNonPetrolNaturalResourceExtraction = 2,
		
		[EnumMemberAttribute()]
		BroadcastingPrintingAndPublishing = 3,
		
		[EnumMemberAttribute()]
		Brokers = 4,
		
		[EnumMemberAttribute()]
		BuildingSupplyRetail = 5,
		
		[EnumMemberAttribute()]
		BusinessServices = 6,
		
		[EnumMemberAttribute()]
		Consulting = 7,
		
		[EnumMemberAttribute()]
		ConsumerServices = 8,
		
		[EnumMemberAttribute()]
		DesignDirectionAndCreativeManagement = 9,
		
		[EnumMemberAttribute()]
		DistributorsDispatchersAndProcessors = 10,
		
		[EnumMemberAttribute()]
		DoctorSOfficesAndClinics = 11,
		
		[EnumMemberAttribute()]
		DurableManufacturing = 12,
		
		[EnumMemberAttribute()]
		EatingAndDrinkingPlaces = 13,
		
		[EnumMemberAttribute()]
		EntertainmentRetail = 14,
		
		[EnumMemberAttribute()]
		EquipmentRentalAndLeasing = 15,
		
		[EnumMemberAttribute()]
		Financial = 16,
		
		[EnumMemberAttribute()]
		FoodAndTobaccoProcessing = 17,
		
		[EnumMemberAttribute()]
		InboundCapitalIntensiveProcessing = 18,
		
		[EnumMemberAttribute()]
		InboundRepairAndServices = 19,
		
		[EnumMemberAttribute()]
		Insurance = 20,
		
		[EnumMemberAttribute()]
		LegalServices = 21,
		
		[EnumMemberAttribute()]
		NonDurableMerchandiseRetail = 22,
		
		[EnumMemberAttribute()]
		OutboundConsumerService = 23,
		
		[EnumMemberAttribute()]
		PetrochemicalExtractionAndDistribution = 24,
		
		[EnumMemberAttribute()]
		ServiceRetail = 25,
		
		[EnumMemberAttribute()]
		SIGAffiliations = 26,
		
		[EnumMemberAttribute()]
		SocialServices = 27,
		
		[EnumMemberAttribute()]
		SpecialOutboundTradeContractors = 28,
		
		[EnumMemberAttribute()]
		SpecialtyRealty = 29,
		
		[EnumMemberAttribute()]
		Transportation = 30,
		
		[EnumMemberAttribute()]
		UtilityCreationAndDistribution = 31,
		
		[EnumMemberAttribute()]
		VehicleRetail = 32,
		
		[EnumMemberAttribute()]
		Wholesale = 33,
	}
}
