//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared.Models.Domain
{
	using System.CodeDom.Compiler;
	using System.Runtime.Serialization;
	
	
	[DataContractAttribute()]
	[GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.95")]
	public enum ActivityPartyParticipationType
	{
		
		[EnumMemberAttribute()]
		Sender = 1,
		
		[EnumMemberAttribute()]
		ToRecipient = 2,
		
		[EnumMemberAttribute()]
		CCRecipient = 3,
		
		[EnumMemberAttribute()]
		BCCRecipient = 4,
		
		[EnumMemberAttribute()]
		RequiredAttendee = 5,
		
		[EnumMemberAttribute()]
		OptionalAttendee = 6,
		
		[EnumMemberAttribute()]
		Organizer = 7,
		
		[EnumMemberAttribute()]
		Regarding = 8,
		
		[EnumMemberAttribute()]
		Owner = 9,
		
		[EnumMemberAttribute()]
		Resource = 10,
		
		[EnumMemberAttribute()]
		Customer = 11,
	}
}
