//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared.Models.Domain
{
	using System.CodeDom.Compiler;
	using System.Runtime.Serialization;
	
	
	[DataContractAttribute()]
	[GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.71")]
	public enum ContactAddressOneShippingMethod
	{
		
		[EnumMemberAttribute()]
		Airborne = 1,
		
		[EnumMemberAttribute()]
		DHL = 2,
		
		[EnumMemberAttribute()]
		FedEx = 3,
		
		[EnumMemberAttribute()]
		UPS = 4,
		
		[EnumMemberAttribute()]
		PostalMail = 5,
		
		[EnumMemberAttribute()]
		FullLoad = 6,
		
		[EnumMemberAttribute()]
		WillCall = 7,
	}
}
