//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared.Models.Domain
{
	using System.CodeDom.Compiler;
	using System.Runtime.Serialization;
	
	
	[DataContractAttribute()]
	[GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.95")]
	public enum GlobalModelTrainingStatus1
	{
		
		[EnumMemberAttribute()]
		PublishInProgress = 326340000,
		
		[EnumMemberAttribute()]
		PublishFailed = 326340002,
		
		[EnumMemberAttribute()]
		PublishCompleted = 326340003,
		
		[EnumMemberAttribute()]
		TrainConfigCreated = 326340001,
		
		[EnumMemberAttribute()]
		TrainingFailed = 326340004,
		
		[EnumMemberAttribute()]
		TrainingInProgress = 326340005,
		
		[EnumMemberAttribute()]
		TrainingCompleted = 326340006,
		
		[EnumMemberAttribute()]
		PublishConfigCreated = 326340007,
		
		[EnumMemberAttribute()]
		Draft = 192350000,
		
		[EnumMemberAttribute()]
		LoadingData = 326340008,
	}
}
