//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared.Models.Domain
{
	using System.CodeDom.Compiler;
	using System.Runtime.Serialization;
	
	
	[DataContractAttribute()]
	[GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.95")]
	public enum LeadLeadSource
	{
		
		[EnumMemberAttribute()]
		Advertisement = 1,
		
		[EnumMemberAttribute()]
		EmployeeReferral = 2,
		
		[EnumMemberAttribute()]
		ExternalReferral = 3,
		
		[EnumMemberAttribute()]
		Partner = 4,
		
		[EnumMemberAttribute()]
		PublicRelations = 5,
		
		[EnumMemberAttribute()]
		Seminar = 6,
		
		[EnumMemberAttribute()]
		TradeShow = 7,
		
		[EnumMemberAttribute()]
		Web = 8,
		
		[EnumMemberAttribute()]
		WordOfMouth = 9,
		
		[EnumMemberAttribute()]
		Other = 10,
	}
}
